[package]
name = "hzrd"
version = "0.0.2"
edition = "2021"
authors = ["Herman Skogseth"]
rust-version = "1.65"
description = "Shared mutability containers based on hazard pointers"
repository = "https://github.com/skogseth/hzrd/"
license = "MIT"
